
export default [
  {
    name: "Cinema App",
    tools: "React | Firebase | Movie API",
    color: "#fcba03",
    id: "1",
    description:
      "This application is a Cinema App the lets the user explore the site and discover movies. For this project I used the movie database API to get all the movies' data. The insipration for this site is a combination of Netflix and HBO themes. Overall this was a fun project to build. The upcoming features are to add video trailers and authentication functionality",
    video: "9HkUCRxMGiA",
    backgroundPic: `/CinemaBackground.png`,
    thumbnail: `/CinemaThumbnail.png`,
    website: "https://cinema-app-eight.vercel.app/",
    github: "https://github.com/007Steve/Cinema-app",
  },
  {
    name: "Twitter Clone",
    tools: "React | Firebase",
    color: "#03A3FF",
    id: "2",
    description: "The Twitter Clone App is a replica of Twitter that I created to challenge myself to see if I could build this particular layout. I used Firebase for the back-end and React for the front-end of this app.",
    backgroundPic: `/TwitterBackground.png`,
    thumbnail: `/TwitterThumbnail.png`,
    video: "nfECKR4MXqQ",
    website: "https://twitter-app-swart.vercel.app/",
    github: "https://github.com/007Steve/Twitter-App",
  },
  {
    name: "AI Voice",
    tools: "HTML | CSS | JavaScript",
    color: "#9AC1F8",
    id: "3",
    description: "This app is using speech recognition and speech synthesis to respond to your questions. As of right now, there are only a few questions programmed. You can try this app out by saying, `Who are you? Why should I hire Steven? Who is Steven?`",
    backgroundPic: `/AIBackground.png`,
    thumbnail: `/AiiThumbnail.png`,
    video: "https://media.giphy.com/media/Y0shUe3fnDpysQFELD/giphy.gif",
    website: "https://ai-voice-app.vercel.app/",
    github: "https://github.com/007Steve/AI-Voice-App",
  },
  {
    name: "Quotes",
    tools: "HTML | CSS | Quotes API",
    color: "#1CD7BD",
    id: "4",
    description: "The quote generator is an app that generates random quotes. I am fetching data from the quote API and I also used CSS animation to give the quote the floating effect.",
    backgroundPic: `/QuoteBackground.png`,
    thumbnail: `/QuoteThumbnail.png`,
    video: "0KeJrm1bSxI",
    website: "https://quotes-generator-nine.vercel.app/",
    github: "https://github.com/007Steve/Quotes-Generator",
  },
  {
    name: "Peloton",
    tools: "React | CSS | Youtube API",
    color: "red",
    id: "5",
    description: "Peleton app is a clone of the Peloton website that provides you with the ability to check different workout videos. I'm using the Youtube API to pull in the videos for the app.",
    backgroundPic: `/PelotonBackground.png`,
    thumbnail: `/PelotonThumbnail.png`,
    video: "IUAYAI1G-Zk",
    website: "https://peloton-clone.vercel.app/",
    github: "https://github.com/007Steve/Peloton-clone",
  },
];
