
export default [
  {
    name: "Cinema App",
    tools: "React | Firebase | Movie API",
    color: "#fcba03",
    id: "1",
    description:
      "This applicationa is a cinema app the let the user explore  the site and discover movies.For this projectt i used the movie database api to get all the movies data. the insipration for this site is a combination of Netfelix and Hbo themses. Overall this was a fun project to build, upcoming featues are to add video trailer,authentication functionality",
    video: "9HkUCRxMGiA",
    backgroundPic: `/CinemaBackground.png`,
    thumbnail: `/CinemaThumbnail.png`,
    website: "https://movie-app-54a42.web.app/",
    github: "https://github.com/007Steve/Cinema-app",
  },
  {
    name: "Twitter Clone",
    tools: "React | Firebase",
    color: "#03A3FF",
    id: "2",
    description: "Have a carpet-like lawn without any work.",
    backgroundPic: `/TwitterBackground.png`,
    thumbnail: `/TwitterThumbnail.png`,
    video: "https://media.giphy.com/media/Y0shUe3fnDpysQFELD/giphy.gif",
    website: "https://twitter-app-swart.vercel.app/",
    github: "https://github.com/007Steve/Twitter-App",
  },
  {
    name: "AI Voice",
    tools: "HTML | CSS | JavaScript",
    color: "#9AC1F8",
    id: "3",
    description: "This app is uses the speech recognition ",
    backgroundPic: `/AIBackground.png`,
    thumbnail: `/AiiThumbnail.png`,
    video: "https://media.giphy.com/media/Y0shUe3fnDpysQFELD/giphy.gif",
    website: "https://ai-voice-app.vercel.app/",
    github: "https://github.com/007Steve/AI-Voice-App",
  },
  {
    name: "Quotes",
    tools: "HTML | CSS | Quotes API",
    color: "#1CD7BD",
    id: "4",
    description: "about random quotes",
    backgroundPic: `/QuoteBackground.png`,
    thumbnail: `/QuoteThumbnail.png`,
    video: "0KeJrm1bSxI",
    website: "https://quotes-generator-nine.vercel.app/",
    github: "https://github.com/007Steve/Quotes-Generator",
  },
  {
    name: "Peloton",
    tools: "HTML | CSS",
    color: "red",
    id: "5",
    description: "Have a carpet-like lawn without any work.",
    backgroundPic: `/PelotonBackground.png`,
    thumbnail: `/PelotonThumbnail.png`,
    video: "DzF1f_uH5uk",
    website: "https://peloton-clone.vercel.app/",
    github: "https://github.com/007Steve/Peloton-clone",
  },
];
